CREATE TABLE IF NOT EXISTS Users
(
  UserID VARCHAR(50) NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  DateJoined DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  BirthDate DATE NOT NULL,
  PRIMARY KEY (UserID)
);

CREATE TABLE IF NOT EXISTS GroupInfo
(
  GroupID INT NOT NULL,
  GroupName VARCHAR(250) NOT NULL,
  PRIMARY KEY (GroupID)
);

CREATE TABLE IF NOT EXISTS Topics
(
  TopicID INT NOT NULL,
  TopicName VARCHAR(250) NOT NULL,
  PRIMARY KEY (TopicID)
);

CREATE TABLE IF NOT EXISTS GroupMembers
(
  UserID VARCHAR(50) NOT NULL,
  GroupID INT NOT NULL,
  PRIMARY KEY (UserID, GroupID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (GroupID) REFERENCES GroupInfo(GroupID)
);

CREATE TABLE IF NOT EXISTS FollowedTopics
(
  UserID VARCHAR(50) NOT NULL,
  TopicID INT NOT NULL,
  PRIMARY KEY (UserID, TopicID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (TopicID) REFERENCES Topics(TopicID)
);

CREATE TABLE IF NOT EXISTS Friends
(
  UserID VARCHAR(50) NOT NULL,
  FriendID VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID, FriendID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (FriendID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS FollowedUsers
(
  UserID VARCHAR(50) NOT NULL,
  FollowedID VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID, FollowedID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (FollowedID) REFERENCES Users(UserID)
);

CREATE TABLE IF NOT EXISTS Posts
(
  PostID INT NOT NULL AUTO_INCREMENT,
  PostTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  Content VARCHAR(1000) NOT NULL,
  UserID VARCHAR(50) NOT NULL,
  GroupID INT,
  TopicID INT,
  ParentPost INT,
  PRIMARY KEY (PostID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (GroupID) REFERENCES GroupInfo(GroupID),
  FOREIGN KEY (TopicID) REFERENCES Topics(TopicID),
  FOREIGN KEY (ParentPost) REFERENCES Posts(PostID)
);

CREATE TABLE IF NOT EXISTS Links
(
  Path VARCHAR(250) NOT NULL,
  PostID INT NOT NULL,
  PRIMARY KEY (Path, PostID),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);

CREATE TABLE IF NOT EXISTS Reactions
(
  Reaction BOOLEAN NOT NULL,
  UserID VARCHAR(50) NOT NULL,
  PostID INT NOT NULL,
  PRIMARY KEY (UserID, PostID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);

CREATE TABLE IF NOT EXISTS ReadStatus
(
  HasRead BOOLEAN NOT NULL,
  UserID VARCHAR(50) NOT NULL,
  PostID INT NOT NULL,
  PRIMARY KEY (UserID, PostID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);
