CREATE TABLE Users
(
  UserID VARCHAR(50) NOT NULL,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  DateJoined DATE NOT NULL,
  BirthDate DATE NOT NULL,
  PRIMARY KEY (UserID)
);

CREATE TABLE GroupInfo
(
  GroupID INT NOT NULL,
  GroupName VARCHAR(250) NOT NULL,
  PRIMARY KEY (GroupID)
);

CREATE TABLE Topics
(
  TopicID INT NOT NULL,
  TopicName VARCHAR(250) NOT NULL,
  PRIMARY KEY (TopicID)
);

CREATE TABLE GroupMembers
(
  UserID VARCHAR(50) NOT NULL,
  GroupID INT NOT NULL,
  PRIMARY KEY (UserID, GroupID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (GroupID) REFERENCES GroupInfo(GroupID)
);

CREATE TABLE FollowedTopics
(
  UserID VARCHAR(50) NOT NULL,
  TopicID INT NOT NULL,
  PRIMARY KEY (UserID, TopicID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (TopicID) REFERENCES Topics(TopicID)
);

CREATE TABLE Friends
(
  UserID VARCHAR(50) NOT NULL,
  FriendID VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID, FriendID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (FriendID) REFERENCES Users(UserID)
);

CREATE TABLE FollowedUsers
(
  UserID VARCHAR(50) NOT NULL,
  FollowedID VARCHAR(50) NOT NULL,
  PRIMARY KEY (UserID, FollowedID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (FollowedID) REFERENCES Users(UserID)
);

CREATE TABLE Posts
(
  PostID INT NOT NULL,
  PostTime DATE NOT NULL,
  Content VARCHAR(1000) NOT NULL,
  UserID VARCHAR(50) NOT NULL,
  GroupID INT,
  TopicID INT,
  ParentPost INT,
  PRIMARY KEY (PostID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (GroupID) REFERENCES GroupInfo(GroupID),
  FOREIGN KEY (TopicID) REFERENCES Topics(TopicID),
  FOREIGN KEY (ParentPost) REFERENCES Posts(PostID)
);

CREATE TABLE Links
(
  Path VARCHAR(250) NOT NULL,
  PostID INT NOT NULL,
  PRIMARY KEY (Path, PostID),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);

CREATE TABLE Reactions
(
  Reaction BOOLEAN NOT NULL,
  UserID VARCHAR(50) NOT NULL,
  PostID INT NOT NULL,
  PRIMARY KEY (UserID, PostID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);

CREATE TABLE ReadStatus
(
  HasRead BOOLEAN NOT NULL,
  UserID VARCHAR(50) NOT NULL,
  PostID INT NOT NULL,
  PRIMARY KEY (UserID, PostID),
  FOREIGN KEY (UserID) REFERENCES Users(UserID),
  FOREIGN KEY (PostID) REFERENCES Posts(PostID)
);
